{
  "formatVersion": "1.1",
  "component": {
    "group": "com.byteutility",
    "module": "safedatastorepreflib",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "safedatastorepreflib-1.0.aar",
          "url": "safedatastorepreflib-1.0.aar",
          "size": 22897,
          "sha512": "2cf781cc36a7203ff54e7c90e146946ac8755ef5e8542b2ded25635130211ff5f51d6a360da04b2ed79810f6011ce630823e4a83536f51e0891462cd847fb2a3",
          "sha256": "3eeaed15d4dfb92184004c05567959750098f0356b15632438cbcef0e3d48fe6",
          "sha1": "53bf0d12253133d938095d7d2284cdd5bce234fc",
          "md5": "91c1ccd9eb68b0130edc4858006ce1cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "safedatastorepreflib-1.0.aar",
          "url": "safedatastorepreflib-1.0.aar",
          "size": 22897,
          "sha512": "2cf781cc36a7203ff54e7c90e146946ac8755ef5e8542b2ded25635130211ff5f51d6a360da04b2ed79810f6011ce630823e4a83536f51e0891462cd847fb2a3",
          "sha256": "3eeaed15d4dfb92184004c05567959750098f0356b15632438cbcef0e3d48fe6",
          "sha1": "53bf0d12253133d938095d7d2284cdd5bce234fc",
          "md5": "91c1ccd9eb68b0130edc4858006ce1cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "safedatastorepreflib-1.0-sources.jar",
          "url": "safedatastorepreflib-1.0-sources.jar",
          "size": 5360,
          "sha512": "94fa72ec8558733d433c84b3551e2cdf25495b2f7d9e3418ddd3a40136beb75d8e46ca646ed6b75aaaaa9584f1d35b46b80de5b5422ae5a9c8576442ee33dedb",
          "sha256": "5f446b009e3644e55da198116d05d2479c5ad63941aaa0ac75c6eee3ef5c293a",
          "sha1": "d222b10153a9ad59753f299fb9b827774d9b6784",
          "md5": "c9172a68960f9b99661aa1aea111a5ea"
        }
      ]
    }
  ]
}
